name: CI/CD Docker Build and Push

on:
  push:
    branches: [ master ] 
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push backend image
      run: |
        docker build -t janastoj/backend ./backend
        docker push janastoj/backend

    - name: Build and push frontend image
      run: |
        docker build -t janastoj/frontend ./frontend
        docker push janastoj/frontend
